export const siteConfig = {
  name: "Ooka Pratama",
  authorName: "Ooka Pratama",
  username: "ookapratama",
  description:
    "Portofolio Profesional Ooka Pratama - Backend Developer berpengalaman dalam membangun sistem berbasis Laravel, aplikasi mobile React Native (AR), dan solusi Machine Learning. Berfokus pada arsitektur kode yang bersih, efisien, dan performa tinggi.",
  url: "https://ooka.my.id",
  links: {
    instagram: "https://instagram.com/ookapratama_",
    github: "https://github.com/ookapratama",
  },
  ogImage: "https://ooka.my.id/ooka1.webp",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Ooka Pratama",
    "Backend Developer",
    "Laravel Developer Indonesia",
    "Machine Learning Engineer",
    "React Native Developer",
    "Web Developer Makassar",
    "Python Developer",
    "Full Stack Developer Laravel & React",
    "Augmented Reality Developer",
    "Sistem Informasi Kearsipan SISKA",
    "Laptop Price Prediction ML",
    "Portofolio Developer Indonesia",
    "Modern Web Development",
    "Clean Code Specialist",
    "AI Automation",
    "AI Automation Specialist",
    "AI Automation Engineer",
    "n8n Automation",
    "Vibe Coding",
  ],
};
