export const siteConfig = {
  name: "Ooka Pratama",
  authorName: "Ooka Pratama",
  username: "ookapratama",
  description:
    "Ooka Pratama's Professional Portfolio - Backend Developer experienced in building Laravel systems, React Native (AR) mobile apps, and Machine Learning solutions. Focused on clean, efficient, and high-performance code architecture.",
  url: "https://ooka.my.id",
  links: {
    instagram: "https://instagram.com/ookapratama_",
    github: "https://github.com/ookapratama",
  },
  ogImage: "https://ooka.my.id/ooka1.webp",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Ooka Pratama",
    "Backend Developer",
    "Laravel Developer Indonesia",
    "Machine Learning Engineer",
    "React Native Developer",
    "Web Developer Makassar",
    "Python Developer",
    "Full Stack Developer Laravel & React",
    "Augmented Reality Developer",
    "SISKA Archiving System",
    "Laptop Price Prediction ML",
    "Indonesia Developer Portfolio",
    "Modern Web Development",
    "Clean Code Specialist",
    "AI Automation",
    "AI Automation Specialist",
    "AI Automation Engineer",
    "n8n Automation",
    "Vibe Coding",
  ],
};
